# Generated by Django 4.1 on 2022-09-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0002_unlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnLike',
        ),
    ]
